version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - run: pytest -q

workflows:
  ci:
    jobs:
      - test
